### PR TITLE
Chore/linting automation

### LINKED ISSUE #1184: Standardize the code linting flow for all contributors
With more developers coming on board we should strive to keep consistency in our code in regards of format, style and syntax. Applying a linting phase bound to the transpilation/versioning phases of development seems a good start.

The idea is to ensure that all developers get their code linted regardless the IDE in use and also get tips and hints on malformed code on dev-time. On a side note, a proper linting upon committing code will reduce the time required for peer-reviewing our code.

**Requirements**

- [x] Update lint config manifest with industry standard conventions for Angular/TypeScript projects whereas required
- [x] Ensure a linting pass is applied upon committing code to the forked repo
- [x] Update all install scripts necessary to make these rules available upon bootstrapping the frontend app
- [x] Refactor and format the code whereas necessary to fulfill the new linter rules.

### PR DESCRIPTION
**Pull request by deeleman**
Fixes #1184 

---
Updates in this PR fall into two categories:

* **Changes in the overall build-for-dev and git-commit processes.** Developers will now take advantage of the latest version of the git hooks available every time they run the start command. In addition, an automated process will be run on every `git commit` attempt in order to audit and lint the code, no matter if the dev leverages `yarn commit` or commits code by hand.
* **Updated actual project files to embrace our new linting conventions.** The linting rules are available at `tslint.json` and they also encompass a particular ruleset to ensure that code commits embrace basic conventions in Angular-land (wrapping interpolated variables in spaces, implementing the proper interface where required, naming components, pipes and selectors according to the official Angular guidelines, etc).

These changes encompass a huge amount of files, but for the sake of flexibility the overall scope has been trimmed down to 70+ files, being the following the only files that will require a more thorough review (changes in the rest of files are purely cosmetic):

* tsint.json
* app.component.ts
* navigation.service.ts
* user.service.ts
* integrations/status.component.ts
* integrations/detail.component.ts

### CODE REVIEW

**Comment by gashcrumb** [comment]
I'm +1 to this after reviewing the changes, I'm gonna actually pull this down and give it a try locally too just to be on the safe side since it touches so many files.

@kahboom I'll give you chance to review and have a look also before I approve it, as of course it'll get merged right away on approval :-)

**Comment by gashcrumb** [comment]
Wonder, do we need to worry about this warning from `yarn lint`:

```
$ yarn ng lint
Warning: The 'no-unused-variable' rule requires type information.
```

**Comment by gashcrumb** [comment]
Yep, so definitely happy with all of this, again will give @kahboom a chance to look too before merging...

**Comment by deeleman** [comment]
Regarding that alert:

`Warning: The 'no-unused-variable' rule requires type information.`

This does not affect the linting process, but it is more of an annoyance I'm afraid. I've bumped the tslint dep to the latest version and now the aforementioned rule, which was superuseful for spotting variables in the code which are not in use, seems to be no longer supported or broken. I am reluctant to remove it since I still want to extend support for it, but unfortunately:

* Angular CLI and Yarn get in the middle;
* Another workaround is to detect unused variables upon compilation by setting up `tsconfig` accordingly, but the compiler will complain because of Atlasmapper since it has literally dozens of loose unused variables that would need to be addressed first;

Let's leave it as is while I find a way to work that rule out.

**Comment by gashcrumb** [comment]
> Let's leave it as is while I find a way to work that rule out.

Yeah, that's fine, I didn't see any problems, just noticed the warning so no big deal :-)

**Pull request merged**
