### PR TITLE
docs(compodoc): Add compodoc with current state as is

### LINKED ISSUE #131: Documentation for UI
Automatically generated documentation could be very useful for encouraging contribution, as we are using many third party dependencies, and many developers are new to Angular 2 on its own. For instance, we are using Angular CLI, and just going through its dependencies, as well as how Webpack works, etc. To facilitate this, it makes sense to have some type of technical overview along with automatically generated documentation.

### PR DESCRIPTION
**Pull request by kahboom**
Add compodoc with automatically generated documentation. This will need cleanup and app-wide documentation, but sets it up and closes #131 .

screenshot 2017-08-17 14 50 01
screenshot 2017-08-17 14 50 14
screenshot 2017-08-17 14 50 25
screenshot 2017-08-17 14 51 18

### CODE REVIEW

**Comment by gashcrumb** [comment]
Is the stuff under `documentation/` all generated, and does that really need to be checked into master?  Seems like that'd be a better thing to generate into gh-pages via CI when PRs are merged...

**Comment by kahboom** [comment]
@gashcrumb - Sure I can _not_ check it in, one sec.

**Comment by kahboom** [comment]
Done @gashcrumb

**Comment by kahboom** [comment]
@gashcrumb sure, sounds good. will look into that momentarily..

**Pull request merged**
