### PR TITLE
fix(auth): Notification toast when refresh token fails

### LINKED ISSUE #217: Add redirect to login page when token times out
Currently only a 401 happens for an Ajax request and the UI doesn't change.

### PR DESCRIPTION
**Pull request by astefanutti**
fixes #217

### CODE REVIEW

**Comment by gashcrumb** [comment]
@astefanutti have some test failures, most likely you need to add the toaster module to `app.component.spec.ts`.  You can run `yarn test` in a second terminal and they'll run whenever you make a change.

**Comment by astefanutti** [comment]
@gashcrumb thx! Still need to assimilate all that 😃.

**Comment by jludvice** [comment]
btw @jimmidyson  why was I assigned to this issue by @jimmibot  ?

**Comment by astefanutti** [comment]
@jludvice it may be it's based on the commit logs, finding the most active contributor intersecting with the PR changes.

**Pull request merged**
