### PR TITLE
[WIP] feat(logout): Add logout support

### LINKED ISSUE #1035: Add "log out" option to user account dropdown
Right now, nothing is available if you click on user icon. Should add a way for users to log out. See screenshot below from [PatternFly](http://www.patternfly.org/pattern-library/application-framework/masthead/). 

image

### PR DESCRIPTION
**Pull request by kahboom**
~WIP as this is an initial pass-thru. Adds 'logout' to dropdown, toast notification, calls oauthService's `logout` method, updates local component var to hide certain items. The oauthService `logout` method is not currently working properly, results in an invalid redirect URI error, which doesn't surprise me as I'm not sure how logout with angular-oauth2-oidc is going to work moving forward without GitHub auth. Some changes will likely need to be made there, or we need an easy way to access the user token easily to delete it.~

Changes:
- Add method to `userService` and call from the `AppComponent`.
- Remove reference to `oauthService`.
- Add Logout to dropdown menu.
- Use new logout endpoint to make direct HTTP call.
- Add toast notification to confirm success/failure of logout request.

cc @jimmidyson 

fix #1035

### CODE REVIEW

**Comment by gashcrumb** [comment]
@kahboom test failure though...  Wonder, should we just eliminate component tests altogether and just put more of our logic in services...

**Comment by gashcrumb** [comment]
Ah, missed the WIP bit

**Comment by kahboom** [comment]
>kahboom dismissed gashcrumb’s stale review via 882c1c9 18 hours ago

woah, I totally did not "dismiss" your review, @gashcrumb. GitHub is getting feisty..  :joy:

**Comment by gashcrumb** [comment]
Is this still WIP?

**Comment by jimmidyson** [comment]
Once #1090 is merged, there will be a proper endpoint, `/oauth/sign_out` to redirect to the logout page so user can be properly logged out. Not sure if it's worth merging this before that?

**Comment by kahboom** [comment]
Probably best to wait imho..

**Comment by kahboom** [comment]
I'll update once the endpoint is ready

**Comment by kahboom** [comment]
Closing and opening a new PR momentarily, as this one is not picking up my latest commits from [here](https://github.com/syndesisio/syndesis-ui/compare/master...kahboom:1035-logout?expand=1) and merge conflicts, for some reason. Perhaps it's been open for too long? :joy:

**Pull request closed without merging**
