### PR TITLE
refactor(connection): Remove old connection view page

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by gashcrumb** [comment]
I think we were going to hold off doing this, but honestly, I don't see us going back to that layout really.  @akieling WDYT?

**Comment by astefanutti** [comment]
@gashcrumb I like removing code 😄!

**Comment by akieling** [comment]
It's fine. I guess we could review the create connection code and see if there is anything from the connection details page that could be reused.

**Comment by gashcrumb** [comment]
@akieling probably worth raising an issue to track that so we don't forget, and I'll go ahead and merge this one...

**Pull request merged**
